#! /bin/bash
check_user()
{
    user=`who | grep $1 | wc -1 `
          if [ $user -eq 0 ]
          then
                return 0 
          else
                return 1
          fi
}
while true   #  program  begin  here
do
       echo   "Input  username: \c"
       read   uname
       check_user  &uname
       if  [ $? -eq 1 ]
       then  echo  "user $uname online"
       else  echo  "user $uname offline"
       fi
done
          
